- hosts: all
  sudo: yes

  tasks:
    - name: enable multiverse
      apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty multiverse' state=present
    - name: install required encoding stuff
      action: apt pkg={{item}} state=installed
      with_items:
      - git-core
      - build-essential
      - tmux
      - htop
      - yasm
      - libfaac0
      - libfaac-dev
      - libass-dev
      - libx264-142
      - libx264-dev
      - libfdk-aac-dev
      - libmp3lame0
      - libmp3lame-dev
      - libopencore-amrnb0
      - libopencore-amrnb-dev
      - libopencore-amrwb0
      - libopencore-amrwb-dev
      - libopenjpeg2
      - libopenjpeg-dev
      - libopus0
      - libopus-dev
      - librtmp0
      - librtmp-dev
      - libschroedinger-1.0-0
      - libschroedinger-dev
      - libspeex1
      - libspeex-dev
      - libtheora0
      - libtheora-dev
      - libvo-aacenc-dev
      - libvo-aacenc0
      - libvorbis0a
      - libvorbis-dev
      - libxvidcore4
      - libxvidcore-dev
      - libavdevice-dev
      - libavdevice53
      - libvpx1
      - libvpx-dev
    - name: checkout-ffmpeg
      git: repo=git://git.videolan.org/ffmpeg.git dest=/usr/src/ffmpeg version=n2.2.3
    - name: build-ffmpeg
      shell: '{{ item }} chdir=/usr/src/ffmpeg creates=/usr/local/bin/ffmpeg'
      with_items:
        - ./configure --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-hardcoded-tables --enable-avresample --enable-vda --cc=cc --host-cflags= --host-ldflags= --enable-libx264 --enable-libfaac --enable-libmp3lame --enable-libxvid --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-aacenc --enable-libass --enable-ffplay --enable-libspeex --enable-libschroedinger --enable-libfdk-aac --enable-libopus --enable-libopenjpeg
        - make -j2
        - make install
        - ldconfig
